### ISSUE TITLE
Mod does not generate config file in correct place (r2modman)

### ISSUE THREAD

**Issue by Gotyam** [Andrew-Flame/Valheim-HotPins#1]
Game version: 0.212.9 (latest current release)
BepInEx version: 5.4.19.0
Mod version: 1.4.2

Note: Was going to post about the previous issue of the config not being generated at all, but saw a new update since I started writing and now it simply generates incorrectly.

Issue: When 100% of other mods generate the config file in the profile location of r2modman, allowing it to be edited through r2modman as well, HotPins stubbornly has its config file in the valheim install directory, default "C:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\config".

Solution: Have a look at how any other mod with a config file generates said file and fix the path, The mod technically works, but it could be fixed up on.

**Comment by Evilur** [comment]
Now in release 1.4.3, the mod generates a configuration file in correct place.
But I haven't found a way to properly configure the mod using the configuration file that is generated by BepInEx, used by most mods. Therefore, the structure of my configuration file differs from the structure of most such files, so it is advisable to use a plain text editor to edit it, not a r2modman config editor.
